Settings:
  Port: 5000
  ServerName: 'lobby'
  Debug: true
Portals:
  LaunchDelayTicks: 20 #Ticks
  LaunchDistanceBlocks: 10 #Blocks
MySQL:
  Host: '127.0.0.1'
  Port: 3306
  Database: 'database'
  Username: 'username'
  Password: 'password'
  TablePrefix: 'cb_'