Settings:
  ServerName: 'lobby'
  Debug: true
Portals:
  Server:
    Port: 5000
    BindAdress: '127.0.0.1'
    AcceptRemoteConnections: true
    PublicAddress: '127.0.0.1'
    SecretKey: 'iliketrains'
  LaunchSpeed: 0.4
  LaunchDelayTicks: 20.0 # Ticks
  LaunchDistanceBlocks: 10.0 # Blocks
MySQL:
  Host: '127.0.0.1'
  Port: 3306
  Database: 'database'
  Username: 'username'
  Password: 'password'
  TablePrefix: 'cb_'