name: CraftBahn
version: ${project.version}
main: de.crafttogether.CraftBahnPlugin
api-version: 1.13
depend: [ CTMySQLAdapter, dynmap, BKCommonLib, Train_Carts, DICore ]
authors: [J0schlZ]
website: https://craft-together.de/
description: Ich mag Züge
commands:
  fahrziel:
    description: Fahrziel wählen
    usage: /fahrziel
  fahrziele:
    description: Fahrziele auflisten
    usage: /fahrziele
  fahrzieledit:
    description: Fahrziele verwalten
    usage: /fahrzieledit
    aliases: [fze]
  rbf:
    description: Teleportiere zu zufälligem Bahnhof
    usage: /rbf
    aliases: [rt, rtp]
  setroute:
    description: Destination silent setzen
    usage: /setroute
  setdestination:
    description: Destination silent setzen
    usage: /setdestination
  mobenter:
    description: Setzt Mobs in den Zug
    usage: /mobenter